name: Run Postman API Collection

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 9 AM Nigeria time
    - cron: '0 11 * * *'  # 12 PM Nigeria time
    - cron: '0 17 * * *'  # 6 PM Nigeria time

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install Newman locally
        run: npm install newman newman-reporter-htmlextra --save-dev

      - name: Create reports folder
        run: mkdir -p ./reports

      - name: Run Postman API collection 
        run: npx newman run restfulApiCopy.postman_collection.json --env-var baseURL=https://api.restful-api.dev --env-var api_Key=44e75bcd-d601-4361-8b6f-f40bcd342ae7 --reporters htmlextra --reporter-htmlextra-export ./reports/report.html

      - name: Run simpleBooks API collection 
        run: npx newman run simpleBooks.postman_collection.json --env-var baseUrl=https://simple-books-api.click --env-var accessToken=3f02aa6ab10bb973bcc6b0279021a4173c26398a514659558edb62ef7deb3c13 --env-var Authentication=1d8d7f97398b896d2ebaa283f6c4a8d88876f50df627ace03dd6fe8032572888 --reporters htmlextra --reporter-htmlextra-export ./reports/report1.html


      - name: Upload HTML Report
        uses: actions/upload-artifact@v5
        with:
          name: newman-report
          path: ./reports/report.html
