
name: Run Postman API Collection

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v5  # Updated to the latest version
        with:
          node-version: '20'  # Specify the Node.js version

      - name: Install Newman and HTMLExtra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra  # Ensure htmlextra reporter is installed

      - name: Run Postman Collection
        run: newman run restful_api.dev_Newman.postman_collection.json  --env-var baseURL=https://api.restful-api.dev --env-var api_Key=44e75bcd-d601-4361-8b6f-f40bcd342ae7 -r htmlextra --reporter-htmlextra-export ./reports/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v5  # Updated to the latest version
        with:
          name: newman-report
          path: ./reports/report.html
